import { Client } from 'kubernetes-client';
export async function listPods() {
  try {
    const client = new Client({ version: '1.16' });
    client.loadFromString(`
      apiVersion: v1
      clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyT0RBNE1EUXhOVEF3SGhjTk1qTXdOREEyTVRnd01qTXdXaGNOTXpNd05EQXpNVGd3TWpNdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyT0RBNE1EUXhOVEF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTTmxVdndkZUxhc01zSWF3MXJXUTRPSFFVMXRSemNqb2EwNkNLQkhNK08KOUxOV1hnMFlNM29BUm9WTFg1SytYRDY0YWt0cGZRSDdwSEZzQnZXdUFLOUhvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUN3WThKbndyN09NRWlWWFlHcGZqCk5YNVd6NEl3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnRHBEbGQ5akJ3d0dRQmlseG0yczdkQUF1dE1OaVBwbHcKY3MvWW9CSlYzWVlDSVFENjc2UVhEUEt1UE1Wd0gwV0RmZ1NOOVdLbDdLZ1U3bXRkQWp6YnoyM2lSUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          server: https://74.220.22.188:6443
        name: dev
      contexts:
      - context:
          cluster: dev
          user: dev
        name: dev
      current-context: dev
      kind: Config
      preferences: {}
      users:
      - name: dev
        user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJSmJGN3prUThySjh3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOamd3T0RBME1UUTVNQjRYRFRJek1EUXdOakU0TURJeU9Wb1hEVEkwTURRdwpOVEU0TURJeU9Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGdEN6WExsNDlxL1dySXYKTnpZSjlqTWpmdkJYTURxYkpBdFAxaHRCNGRkQ1RhZDF3MzVxT2Z5OHRSMG1zZHVWeGJwbXd2Y1pDdGpvaUQxKwp1ckk3bml5alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUXhtSVBYNFZmN2VCRXhsbEpEV3oxZ2h1cmRpVEFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlBaGQrUVBlK2dmK2pVd1JVbHlEWFZaUmp3V0w3V1lzbmRUdnk1UFhpV0JxZ0loQUxnRXVEZ1U4cks2aWtEMgpIUHJqOEdpVTBZbkxDdSs4TUVCZDlOakNBM3lHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyT0RBNE1EUXhORGt3SGhjTk1qTXdOREEyTVRnd01qSTVXaGNOTXpNd05EQXpNVGd3TWpJNQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyT0RBNE1EUXhORGt3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSOUVWL0dzUko0SkxBai9lVUI2R1lTUHI3cmlwR3VQVFM0VHRoREY4ZGcKdWRjaEhTZFNGQm5jU0NZSnlYdWxuekVzdlYzTXJ3bktwL3pFSXFOakF5S1pvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVU1aaUQxK0ZYKzNnUk1aWlNRMXM5CllJYnEzWWt3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnYmt0a2cvbjBGaUs1YVREM3ppSDBhaVRqWEYxVWhCK0sKRjJIOCtPR1M1TjBDSVFEQ3p3ZTMyWXk3N28rbmlzNGJkbS85Mno1VGJmVmd5aWNkekJJY3MyYkVsQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU14bjMrSjlRQU43NmNzTThwLzFzbUp2QklQVG1waWt4OUJJMW5pb0hmRVdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVzBMTmN1WGoycjlhc2k4M05nbjJNeU4rOEZjd09wc2tDMC9XRzBIaDEwSk5wM1hEZm1vNQovTHkxSFNheDI1WEZ1bWJDOXhrSzJPaUlQWDY2c2p1ZUxBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    `);

    await client.loadSpec();
    const pods = await client.api.v1.pods.get();
    console.log('Pods:');
    console.log(pods.body.items);
   } catch (error) {
    console.error('Error:', error);
  }
}

listPods();
